# Cardnews configuration example

fonts:
  title:
    path: Pretendard-Bold.otf
    size: 72
  subtitle:
    path: Pretendard-Regular.otf
    size: 42
  business:
    path: Pretendard-Regular.otf
    size: 36

image:
  width: 1080
  height: 1080
  overlay: true

gemini:
  model: gemini-2.5-flash
  image_model: gemini-2.5-flash-image

brand_card:
  overlay: true
  overlay_alpha: 48
  shadow: false
  fonts:
    brand:
      path: Pretendard-Regular.otf
      size: 24
    title:
      path: Pretendard-Bold.otf
      size: 72
    subtitle:
      path: Pretendard-Regular.otf
      size: 42
    footer:
      path: Pretendard-Regular.otf
      size: 28
